export interface PartnerToken {
  accessToken: string;
  tokenType: string;
  expiresAt: Date;
}

export type TenantToken = PartnerToken;

export interface TenantCredential {
  credentialUuid: string;
  tenantUuid: string;
  clientId: string;
  clientSecret: string;
}

/**
 * A tenant (space) inside one of the partner's applications.
 *
 * `slug` is generated by the platform from the name, and `contactEmail` is
 * `null` for a tenant created without one.
 *
 * `externalId` is the partner's own id for the organisation: the value its
 * subject tokens carry in the tenant claim, unique within the application. A
 * federated login reaches the tenant only through it, so a tenant with none
 * (`null`) cannot be logged into.
 */
export interface Tenant {
  uuid: string;
  applicationUuid: string;
  name: string;
  slug: string;
  contactEmail: string | null;
  externalId: string | null;
  status: string;
  createdAt: Date;
}

/**
 * A user inside one of the partner's tenants.
 *
 * `externalId` is the partner's own id for the person: the value its subject
 * tokens carry in the user claim (`sub` by default), unique within the tenant.
 * A federated login finds the user by it, never by email, so a user with none
 * (`null`) is one no federated login reaches. A user the partner creates
 * starts `pending` and cannot log in until activated.
 */
export interface User {
  uuid: string;
  tenantUuid: string;
  name: string;
  email: string;
  externalId: string | null;
  status: string;
  createdAt: Date;
}

/**
 * Which claim carries each identity value.
 *
 * Shared by the two halves of a federation setup: the issuer that writes the
 * claims and the identity provider row that tells the platform where to read
 * them. Pass one value to both and they cannot drift apart.
 */
export interface SubjectTokenClaimNames {
  user: string;
  tenant: string;
  email: string;
  name: string;
}

/**
 * The tenant a federated login creates when it is that tenant's first.
 *
 * What `createTenant` takes, less the application, which is the identity
 * provider's. The platform generates the slug from `name`. It travels as the
 * subject token's `tenant_profile` claim, which the platform reads only when no
 * tenant of that application has the external id and the provider allows
 * just-in-time tenants. It never updates a tenant that exists.
 *
 * `externalTenantId` is the `externalId` `createTenant` takes: the
 * organisation's id in your own system. The login sends it once, as the
 * token's tenant claim, never inside `tenant_profile`, so `federatedLogin`
 * needs no `externalTenantId` of its own when the profile carries one, and
 * refuses one that differs.
 *
 * `planCode`, also optional, is the one addition: the `planCode` of one of the
 * partner's {@link TenantPlan}s, matched exactly. The tenant is then created
 * subscribed to that plan, monthly and active, as `subscribeTenant` leaves it
 * by default, or not created at all: a code none of the partner's plans has
 * refuses the login with `invalid_target`. Without one the new tenant has no
 * plan.
 */
export interface TenantProfile {
  name: string;
  /** Optional: omitted or `null`, the claim carries no `contact_email`. */
  contactEmail?: string | null;
  /** Optional: omitted or `null`, the claim carries no `plan_code`. */
  planCode?: string | null;
  /** Optional: omitted or `null`, the login's own `externalTenantId` names the tenant. */
  externalTenantId?: string | null;
}

/**
 * The platform's trust anchor for one partner issuer. It belongs to one of the
 * partner's applications: a token it signs logs users into that application's
 * tenants only. Every field is an instruction to the platform's token
 * validator; a subject token overrides none of them. `allowJitTenants` lets a
 * login create its tenant from the token's `tenant_profile` claim, and needs
 * `allowJitUsers`.
 */
export interface IdentityProvider {
  uuid: string;
  applicationUuid: string;
  name: string;
  issuer: string;
  /** The issuer's origin: the only host the platform fetches its keys from. */
  issuerOrigin: string;
  /** Where on `issuerOrigin` the platform fetches the issuer's keys. */
  jwksPath: string;
  /**
   * `issuerOrigin + jwksPath`, the URL the platform fetches. Kept for code that
   * reads it; the platform no longer sends it, so it is derived.
   */
  jwksUrl: string;
  allowedAudiences: string[];
  allowedAlgorithms: string[];
  tokenMaxAgeSeconds: number;
  requireEmailVerified: boolean;
  claimNames: SubjectTokenClaimNames;
  allowJitUsers: boolean;
  /** False from a platform that predates just-in-time tenants. */
  allowJitTenants: boolean;
  status: string;
  createdAt: Date;
}

/**
 * The platform session a subject token was exchanged for.
 *
 * `accessToken` is opaque — not a JWT — and is presented as a bearer credential
 * on the Gateway job APIs. There are no refresh tokens: when it expires, the
 * partner signs a new subject token and exchanges again.
 */
export interface FederatedSession {
  accessToken: string;
  tokenType: string;
  issuedTokenType: string;
  expiresIn: number;
  expiresAt: Date;
  userUuid: string;
  name: string;
  email: string;
  /** The tenant the session belongs to; null from a platform that omits it. */
  tenantUuid: string | null;
  /**
   * True only for the login that created its tenant from a {@link TenantProfile};
   * false from a platform that omits it. Unless that profile named a plan by
   * `planCode`, a new tenant has no plan and draws on the partner's credits
   * uncapped, so subscribe it when this is true.
   */
  tenantCreated: boolean;
}

/** One RSA public signing key, as served in a JWKS (RFC 7517). */
export interface JsonWebKey {
  kty: string;
  use: string;
  alg: string;
  kid: string;
  n: string;
  e: string;
}

/** The document a partner serves at `<issuer>/.well-known/jwks.json`. */
export interface JsonWebKeySet {
  keys: JsonWebKey[];
}

export interface CreateIdentityProviderInput {
  /**
   * The application the provider belongs to. Its tokens log users into that
   * application's tenants only, and every provider of one application must
   * sign the same tenant and user ids.
   */
  applicationUuid: string;
  name: string;
  issuer: string;
  /**
   * Where the platform fetches the issuer's keys: a path on the issuer's
   * origin, under `/.well-known/`. Defaults to `/.well-known/jwks.json`, the
   * platform's default; a `SubjectTokenIssuer`'s is its `jwksPath`.
   */
  jwksPath?: string;
  /**
   * @deprecated Pass `jwksPath`. Only this URL's path is sent, so it must be on
   * the issuer's own origin and carry no query or fragment; anything else, or
   * passing both, throws a `TypeError` before any request.
   */
  jwksUrl?: string;
  allowedAudiences: string[];
  allowedAlgorithms?: string[];
  tokenMaxAgeSeconds?: number;
  requireEmailVerified?: boolean;
  allowJitUsers?: boolean;
  /**
   * Let a login whose tenant claim names no tenant of the application create
   * it, from the `tenant` passed to `federatedLogin`. Requires `allowJitUsers`:
   * the platform answers 422 to one without the other.
   */
  allowJitTenants?: boolean;
  claimNames?: Partial<SubjectTokenClaimNames>;
}

export interface FederatedLoginInput {
  subject: string;
  /**
   * The tenant claim. May be left out when `tenant` carries one, and must
   * equal it when both are given.
   */
  externalTenantId?: string;
  email?: string;
  name?: string;
  emailVerified?: boolean;
  extraClaims?: Record<string, unknown>;
  /**
   * The tenant to create if this is its first login, on a provider that allows
   * just-in-time tenants. The exchange's `tenant_created` says whether that
   * login created it.
   */
  tenant?: TenantProfile;
}

export interface CreateTenantInput {
  applicationUuid: string;
  /** The platform generates the tenant's slug from it. */
  name: string;
  /** Optional: omitted or `null`, the tenant has none. */
  contactEmail?: string | null;
  /**
   * The id your subject tokens carry in the tenant claim, unique within the
   * application. Omit it and set it later with `setTenantExternalId`.
   */
  externalId?: string | null;
}

export interface SetTenantExternalIdInput {
  tenantUuid: string;
  /** Required: `null` clears it, which stops federated logins into the tenant. */
  externalId: string | null;
}

export interface IssueTenantTokenInput {
  clientId: string;
  clientSecret: string;
  forceRefresh?: boolean;
}

export interface SetUserPersonaInput {
  userUuid: string;
  persona: string;
  tenantClientId: string;
  tenantClientSecret: string;
}

export interface CreateUserInput {
  name: string;
  email: string;
  tenantClientId: string;
  tenantClientSecret: string;
  /** The id your subject tokens carry in the user claim (`sub` by default). */
  externalId?: string | null;
}

export interface UpdateUserStatusInput {
  userUuid: string;
  status: "active" | "deactivated";
  tenantClientId: string;
  tenantClientSecret: string;
}

/**
 * A plan the partner offers its own tenants.
 *
 * `credits` is the tenant's included balance and `userCreditsCap` the per-user
 * share of it; both become child-cap rows when a subscription is activated.
 */
export interface TenantPlan {
  uuid: string;
  name: string;
  /**
   * The partner's own code for the plan, unique among its tenant plans and
   * matched exactly: a {@link TenantProfile} names the plan its tenant is
   * created on by it. Set in the Admin Dashboard or the partner plan API; null
   * for a plan without one, and from a platform that predates plan codes.
   */
  planCode: string | null;
  monthlyPriceCents: number;
  yearlyPriceCents: number;
  tpm: number;
  rpm: number;
  credits: number;
  userCreditsCap: number;
  userTpm: number;
  userRpm: number;
}

/**
 * A subscription linking a subscriber to a plan for a billing period.
 *
 * `status` is `pending_payment` until activated, then `paid`. The window
 * (`subscribedFrom`/`subscribedTo`) is null while pending — it is established
 * at activation and is what makes the plan and its balance active.
 */
export interface PlanSubscription {
  uuid: string;
  status: string;
  planType: string;
  billingCycle: string;
  subscribedFrom: Date | null;
  subscribedTo: Date | null;
  paymentTransactionUuid: string | null;
  createdAt: Date;
}

/** One balance row an activation created. */
export interface ProvisionedCap {
  child: string;
  id: number;
  cap: number;
}

/**
 * The balance rows an activation created. A tenant subscription provisions
 * `capsCreated` and never a pool: tenants draw on their partner's credit pool,
 * bounded by those caps.
 */
export interface ProvisionedBalance {
  poolCreated: boolean;
  poolCredits: number;
  capsCreated: ProvisionedCap[];
}

/**
 * A subscription plus whatever its activation provisioned.
 *
 * `provisioned` is null when this call provisioned nothing — the subscription
 * is still pending payment, or an already-active one was activated again
 * (activation is idempotent).
 */
export interface TenantSubscription {
  subscription: PlanSubscription;
  provisioned: ProvisionedBalance | null;
}

export interface SubscribeTenantInput {
  tenantUuid: string;
  planUuid: string;
  billingCycle?: "monthly" | "yearly";
  /** Defaults to true: create AND activate in one call. */
  activateNow?: boolean;
  /** Free text kept in the platform's audit trail (invoice number, note). */
  reference?: string;
}

export interface ActivateTenantSubscriptionInput {
  subscriptionUuid: string;
  reference?: string;
}

/** One plan a top-up package is offered to. */
export interface TopupPackagePlan {
  planType: "partner_plans" | "tenant_plans";
  planUuid: string;
  planName: string;
}

/**
 * A credit bundle the partner sells to its own tenants.
 *
 * `plans` is what makes the offer differ per plan: empty means every tenant
 * sees the package, and one entry confines it to that tenant plan.
 * `validityDays` is null when the purchased credits never expire.
 */
export interface TopupPackage {
  uuid: string;
  name: string;
  credits: number;
  priceCents: number;
  validityDays: number | null;
  status: string;
  audience: string | null;
  plans: TopupPackagePlan[];
}

/**
 * One tenant's purchase of a top-up package.
 *
 * `credits` is snapshotted at purchase time, so editing the package later
 * never changes what an existing purchase granted. `validTo` is null when the
 * credits never expire.
 */
export interface TopupPurchase {
  uuid: string;
  tenantUuid: string;
  tenantName: string;
  packageUuid: string | null;
  packageName: string | null;
  credits: number;
  status: string;
  validFrom: Date | null;
  validTo: Date | null;
  createdAt: Date;
}

/**
 * The credit pool an activated top-up created. Unlike a tenant plan — which
 * provisions caps against the partner's pool — a tenant top-up creates a pool
 * the tenant owns outright, spent before the partner's own credits.
 */
export interface ProvisionedTopup {
  poolCreated: boolean;
  poolCredits: number;
}

/**
 * A tenant's top-up plus whatever its activation provisioned.
 *
 * `provisioned` is null when this call provisioned nothing — the purchase is
 * still pending, or an already-active one was activated again (activation is
 * idempotent).
 */
export interface TenantTopup {
  purchase: TopupPurchase;
  provisioned: ProvisionedTopup | null;
}

export interface CreateTopupPackageInput {
  name: string;
  credits: number;
  priceCents: number;
  /** Omit for credits that never expire. */
  validityDays?: number | null;
  /** Your own tenant plans; omit to offer the package to every tenant. */
  planUuids?: string[];
}

export interface UpdateTopupPackageInput {
  packageUuid: string;
  name?: string;
  credits?: number;
  priceCents?: number;
  validityDays?: number | null;
  status?: "active" | "inactive";
  /** Omit to keep the current scoping; `[]` clears it. */
  planUuids?: string[];
}

export interface GrantTenantTopupInput {
  tenantUuid: string;
  packageUuid: string;
  /** Defaults to true: grant AND activate in one call. */
  activateNow?: boolean;
  /** Free text kept in the platform's audit trail (invoice number, note). */
  reference?: string;
}

export interface ActivateTenantTopupInput {
  transactionUuid: string;
  reference?: string;
}
