<?php

namespace IOCloud\Laravel\Data;

use DateTimeImmutable;

/**
 * A tenant (space) inside one of the partner's applications.
 *
 * `slug` is generated by the platform from the name, and `contactEmail` is
 * null for a tenant created without one.
 *
 * `externalId` is the partner's own id for the organisation: the value its
 * subject tokens carry in the tenant claim, unique within the application. A
 * federated login reaches the tenant only through it, so a tenant with none
 * (null) cannot be logged into.
 */
final readonly class Tenant
{
    public function __construct(
        public string $uuid,
        public string $applicationUuid,
        public string $name,
        public string $slug,
        public ?string $contactEmail,
        public ?string $externalId,
        public string $status,
        public DateTimeImmutable $createdAt,
    ) {
    }

    /** @param array<string, mixed> $payload */
    public static function fromPayload(array $payload): self
    {
        $contactEmail = $payload['contact_email'] ?? null;
        $externalId = $payload['external_id'] ?? null;

        return new self(
            uuid: (string) $payload['uuid'],
            applicationUuid: (string) $payload['application_uuid'],
            name: (string) $payload['name'],
            slug: (string) $payload['slug'],
            contactEmail: $contactEmail === null ? null : (string) $contactEmail,
            externalId: $externalId === null ? null : (string) $externalId,
            status: (string) $payload['status'],
            createdAt: new DateTimeImmutable((string) $payload['created_at']),
        );
    }
}
